#!/bin/bash

# Copyright (c) 2023 Joshua Paine
#
# Permission is hereby granted, free of charge, to any person obtaining a copy 
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
# copies of the Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

printf "
iCloud Calendar URLs
====================
"

PRINCIPAL_URL=`/usr/bin/sqlite3 ~/Library/Calendars/Calendar.sqlitedb "select cached_external_info from Store where type=2 limit 1" | grep -oe "p\\d\+-caldav.icloud.com"`
/usr/bin/sqlite3 -list ~/Library/Calendars/Calendar.sqlitedb << SQL
SELECT char(10) || '* ' || title || ' (' || shared_owner_name || ')' ||
  char(10) || '  ' ||
  'https://$PRINCIPAL_URL' ||
  Calendar.external_id
FROM Calendar JOIN Store ON Calendar.store_id = Store.ROWID
WHERE Store.type = 2 ORDER BY Calendar.display_order
SQL
